CREATE TABLE trades(transaction_id INTEGER PRIMARY KEY REFERENCES transactions(transaction_id), product_id TEXT NOT NULL, listing_id TEXT, position_scope_id INTEGER NOT NULL REFERENCES position_scopes(position_scope_id), side TEXT NOT NULL CHECK(side IN ('BUY','SELL')), quantity TEXT NOT NULL CHECK(typeof(quantity)='text'), price TEXT NOT NULL CHECK(typeof(price)='text'), trade_date TEXT NOT NULL, trade_time TEXT, scheduled_settlement_date TEXT);
CREATE TABLE trade_fees(trade_transaction_id INTEGER NOT NULL REFERENCES trades(transaction_id), fee_type TEXT NOT NULL CHECK(fee_type IN ('COMMISSION','EXCHANGE_FEE','REGULATORY_FEE','OTHER')), amount TEXT NOT NULL CHECK(typeof(amount)='text'), PRIMARY KEY(trade_transaction_id,fee_type));
CREATE TABLE position_entries(position_entry_id INTEGER PRIMARY KEY AUTOINCREMENT, source_transaction_id INTEGER NOT NULL UNIQUE REFERENCES transactions(transaction_id));
CREATE TABLE position_lines(position_line_id INTEGER PRIMARY KEY AUTOINCREMENT, position_entry_id INTEGER NOT NULL REFERENCES position_entries(position_entry_id), position_id INTEGER NOT NULL REFERENCES positions(position_id), line_type TEXT NOT NULL CHECK(line_type IN ('OWNERSHIP','LOCATION')), quantity_delta TEXT NOT NULL CHECK(typeof(quantity_delta)='text'), owner_id INTEGER REFERENCES owners(owner_id), position_scope_id INTEGER REFERENCES position_scopes(position_scope_id), CHECK((line_type='OWNERSHIP' AND owner_id IS NOT NULL AND position_scope_id IS NULL) OR (line_type='LOCATION' AND position_scope_id IS NOT NULL AND owner_id IS NULL)));
CREATE TABLE position_cost_basis_lots(cost_basis_lot_id INTEGER PRIMARY KEY AUTOINCREMENT, source_transaction_id INTEGER NOT NULL UNIQUE REFERENCES transactions(transaction_id), position_id INTEGER NOT NULL REFERENCES positions(position_id), owner_id INTEGER NOT NULL REFERENCES owners(owner_id), position_scope_id INTEGER NOT NULL REFERENCES position_scopes(position_scope_id), quantity_acquired TEXT NOT NULL CHECK(typeof(quantity_acquired)='text'), book_cost_basis TEXT NOT NULL CHECK(typeof(book_cost_basis)='text'));
CREATE TABLE position_cost_basis_allocations(investment_journal_line_id INTEGER NOT NULL REFERENCES journal_lines(journal_line_id), source_cost_basis_lot_id INTEGER NOT NULL REFERENCES position_cost_basis_lots(cost_basis_lot_id), quantity_disposed TEXT NOT NULL CHECK(typeof(quantity_disposed)='text'), book_cost_disposed TEXT NOT NULL CHECK(typeof(book_cost_disposed)='text'), PRIMARY KEY(investment_journal_line_id,source_cost_basis_lot_id));
CREATE INDEX ix_position_bucket ON position_lines(position_id,position_scope_id);
CREATE INDEX ix_lot_bucket ON position_cost_basis_lots(position_id,owner_id,position_scope_id);
CREATE INDEX ix_trade_scope ON trades(position_scope_id,transaction_id);
