"""Deterministic journal generation: canonical CSVs -> ledger/generated/**.

``build_files()`` is pure: it reads the portfolio CSVs and the bridge
mapping and returns {relative path -> file text}. ``generate()`` wholesale
replaces the ``ledger/generated/`` directory with that output. Running it
twice on unchanged inputs produces byte-identical files — idempotency by
determinism; the vihara-data git diff is the review surface.

Every generated transaction carries backlink metadata (``trade_id:`` /
``row_hash:`` / ``source:`` file:line) and a ``^t.<id>`` link. Realized
P&L numbers come from records.cost_basis (the single computation owner);
the ledger's Sigma=0 check re-verifies them at load time.

Sign/shape conventions (see docs/20 in the ledger module):
  buy       Positions +qty {{qty*price+fee, date, "t:ID"}} / Cash -(total)
  sell      Positions -take {lot_date, "t:LOTID"} per consumed lot @ price
            / Cash +(qty*price-fee) / PnL -(realized)
  dividend  Cash +net / Withholding +tax / Dividends -(gross)
  cashflow  Cash +amount / counter -(amount)
  opening   Positions +qty {{qty*avg_cost, as_of, "t:opening"}} / Equity:Opening
Checkpoints become balance assertions dated as_of + 1 day (assertions hold
at the start of a day; checkpoints include the day's trades).
"""

from __future__ import annotations

import datetime
import re
import shutil
from dataclasses import dataclass, field
from decimal import Decimal
from pathlib import Path

from ledger.core import model
from ledger.errors import SourcePos
from ledger.format import format_directives

from ..records.cost_basis import calculate_position
from ..records.imports import (
    TradeImportRow,
    read_cash_checkpoints_csv,
    read_cashflow_import_csv,
    read_dividend_import_csv,
    read_position_snapshots_csv,
    read_trade_import_csv,
)
from ..records.models import (
    CashCheckpoint,
    Cashflow,
    DividendPayment,
    OpeningPosition,
    PositionSnapshot,
    SnapshotKind,
    Trade,
    TradeSide,
)
from .commodities import to_commodity
from .mapping import AccountMapping, BridgeMapping, load_mapping

HEADER = (
    "; GENERATED by portfolio_manager.ledger_bridge - DO NOT EDIT.\n"
    "; Source of truth: the portfolio/ CSVs in this data repo.\n"
    "; Regenerate: python -m portfolio_manager.ledger_bridge generate\n"
)

GENERATED_POS = SourcePos("generated", 0)

OPENING_LABEL = "t:opening"

ONE_DAY = datetime.timedelta(days=1)


@dataclass
class AccountInputs:
    trades: list[tuple[TradeImportRow, str]] = field(default_factory=list)
    dividends: list[tuple[DividendPayment, str]] = field(default_factory=list)
    cashflows: list[tuple[Cashflow, str]] = field(default_factory=list)
    openings: dict[str, PositionSnapshot] = field(default_factory=dict)
    checkpoint_positions: list[PositionSnapshot] = field(default_factory=list)
    checkpoint_cash: list[CashCheckpoint] = field(default_factory=list)


@dataclass
class BuildResult:
    files: dict[str, str]
    warnings: list[str]


def _dedup(items, key_fn, kind: str, warnings: list[str]):
    seen: set[str] = set()
    out = []
    for item, source in items:
        key = key_fn(item)
        if key in seen:
            warnings.append(f"duplicate {kind} row skipped: {source}")
            continue
        seen.add(key)
        out.append((item, source))
    return out


def read_inputs(data_dir: Path, warnings: list[str]) -> dict[str, AccountInputs]:
    portfolio = data_dir / "portfolio"
    inputs: dict[str, AccountInputs] = {}

    def account(account_id: str) -> AccountInputs:
        return inputs.setdefault(account_id, AccountInputs())

    for path in sorted((portfolio / "trades").rglob("*.csv")) if (portfolio / "trades").is_dir() else []:
        rel = path.relative_to(data_dir)
        for i, row in enumerate(read_trade_import_csv(path)):
            account(row.trade.account_id).trades.append((row, f"{rel}:{i + 2}"))
    for path in sorted((portfolio / "dividends").rglob("*.csv")) if (portfolio / "dividends").is_dir() else []:
        rel = path.relative_to(data_dir)
        for i, payment in enumerate(read_dividend_import_csv(path)):
            account(payment.account_id).dividends.append((payment, f"{rel}:{i + 2}"))
    for path in sorted((portfolio / "cashflows").rglob("*.csv")) if (portfolio / "cashflows").is_dir() else []:
        rel = path.relative_to(data_dir)
        for i, flow in enumerate(read_cashflow_import_csv(path)):
            account(flow.account_id).cashflows.append((flow, f"{rel}:{i + 2}"))

    opening_csv = portfolio / "snapshots" / "opening.csv"
    if opening_csv.exists():
        for snapshot in read_position_snapshots_csv(opening_csv, SnapshotKind.OPENING):
            account(snapshot.account_id).openings[snapshot.instrument_id] = snapshot
    checkpoints = portfolio / "checkpoints"
    if checkpoints.is_dir():
        for path in sorted(checkpoints.rglob("positions.csv")):
            for snapshot in read_position_snapshots_csv(path, SnapshotKind.CHECKPOINT):
                account(snapshot.account_id).checkpoint_positions.append(snapshot)
        for path in sorted(checkpoints.rglob("cash.csv")):
            for checkpoint in read_cash_checkpoints_csv(path):
                account(checkpoint.account_id).checkpoint_cash.append(checkpoint)

    # Apply the SAME dedup the records import applies, so both derivations
    # of the text (SQLite and journal) agree.
    for acc in inputs.values():
        acc.trades = _dedup(
            acc.trades,
            lambda r: r.trade.external_trade_id or r.row_hash,
            "trade", warnings,
        )
        acc.dividends = _dedup(
            acc.dividends,
            lambda p: p.external_id or p.row_hash,
            "dividend", warnings,
        )
        acc.cashflows = _dedup(
            acc.cashflows,
            lambda f: f.external_id or f.row_hash,
            "cashflow", warnings,
        )
    return inputs


def _trade_key(row: TradeImportRow) -> str:
    return row.trade.external_trade_id or row.row_hash[:12]


def _link(raw: str) -> str:
    return "t." + re.sub(r"[^A-Za-z0-9\-_/.]", "-", raw)


def _amount(number: Decimal, currency: str) -> model.Amount:
    return model.Amount(number, currency)


def _txn(date, narration, meta, links, postings) -> model.Transaction:
    return model.Transaction(
        date, meta, GENERATED_POS, "*", None, narration,
        frozenset(), frozenset(links), tuple(postings),
    )


def _build_account_directives(
    mapping: AccountMapping,
    opening_account: str,
    uncategorized: str,
    inputs: AccountInputs,
) -> tuple[list[model.Directive], list[model.Directive], dict[str, datetime.date]]:
    """Returns (transactions, assertions, commodity first-use dates)."""
    txns: list[tuple[tuple, model.Transaction]] = []  # (sort key, txn)
    commodity_first_use: dict[str, datetime.date] = {}

    def note_commodity(instrument_id: str, date: datetime.date) -> str:
        commodity = to_commodity(instrument_id)
        first = commodity_first_use.get(commodity)
        if first is None or date < first:
            commodity_first_use[commodity] = date
        return commodity

    # --- opening anchors -------------------------------------------------
    for instrument_id in sorted(inputs.openings):
        snapshot = inputs.openings[instrument_id]
        commodity = note_commodity(instrument_id, snapshot.as_of)
        total = snapshot.quantity * snapshot.average_cost
        postings = [
            model.Posting(
                mapping.positions,
                _amount(snapshot.quantity, commodity),
                model.CostSpec(total, snapshot.currency, snapshot.as_of,
                               OPENING_LABEL, is_total=True),
            ),
            model.Posting(opening_account, _amount(-total, snapshot.currency)),
        ]
        txn = _txn(
            snapshot.as_of,
            f"opening position {instrument_id}",
            {"source": "portfolio/snapshots/opening.csv"},
            [],
            postings,
        )
        txns.append(((snapshot.as_of, 0, instrument_id), txn))

    # --- trades -----------------------------------------------------------
    by_instrument: dict[str, list[tuple[TradeImportRow, str]]] = {}
    for row, source in inputs.trades:
        by_instrument.setdefault(row.trade.instrument_id, []).append((row, source))

    for instrument_id in sorted(by_instrument):
        rows = by_instrument[instrument_id]
        row_by_trade: dict[Trade, tuple[TradeImportRow, str]] = {
            row.trade: (row, source) for row, source in rows
        }
        trades = [row.trade for row, _ in rows]
        opening_snapshot = inputs.openings.get(instrument_id)
        opening = (
            OpeningPosition(
                as_of=opening_snapshot.as_of,
                quantity=opening_snapshot.quantity,
                average_cost=opening_snapshot.average_cost,
                currency=opening_snapshot.currency,
            )
            if opening_snapshot is not None
            else None
        )
        result = calculate_position(trades, mapping.cost_method, opening)
        realized_iter = iter(result.realized_trades)

        ordered = sorted(trades, key=lambda t: (t.trade_date, t.trade_id or ""))
        for seq, trade in enumerate(ordered):
            row, source = row_by_trade[trade]
            commodity = note_commodity(instrument_id, trade.trade_date)
            key = _trade_key(row)
            meta: model.Meta = {}
            if trade.external_trade_id:
                meta["trade_id"] = trade.external_trade_id
            meta["row_hash"] = row.row_hash
            meta["source"] = source
            if row.settle_date is not None:
                meta["settle_date"] = row.settle_date

            if trade.side is TradeSide.BUY:
                total = trade.quantity * trade.price + trade.fee
                postings = [
                    model.Posting(
                        mapping.positions,
                        _amount(trade.quantity, commodity),
                        model.CostSpec(total, trade.currency, trade.trade_date,
                                       f"t:{key}", is_total=True),
                    ),
                    model.Posting(mapping.cash, _amount(-total, trade.currency)),
                ]
                narration = (
                    f"buy {trade.quantity} {instrument_id} @ {trade.price}"
                    + (f", fee {trade.fee}" if trade.fee else "")
                )
            else:
                realized = next(realized_iter)
                proceeds = realized.proceeds
                postings = []
                for lot in realized.consumed_lots:
                    if mapping.booking == "NONE":
                        spec = model.CostSpec()  # pool reduction: empty {}
                    elif lot.source_trade is None:
                        assert opening is not None
                        spec = model.CostSpec(date=opening.as_of, label=OPENING_LABEL)
                    else:
                        source_row, _ = row_by_trade[lot.source_trade]
                        spec = model.CostSpec(
                            date=lot.source_trade.trade_date,
                            label=f"t:{_trade_key(source_row)}",
                        )
                    postings.append(
                        model.Posting(
                            mapping.positions,
                            _amount(-lot.quantity, commodity),
                            spec,
                            price=_amount(trade.price, trade.currency),
                        )
                    )
                postings.append(model.Posting(mapping.cash, _amount(proceeds, trade.currency)))
                postings.append(
                    model.Posting(mapping.pnl, _amount(-realized.realized_pnl, trade.currency))
                )
                narration = (
                    f"sell {trade.quantity} {instrument_id} @ {trade.price}"
                    + (f", fee {trade.fee}" if trade.fee else "")
                )

            txn = _txn(trade.trade_date, narration, meta, [_link(key)], postings)
            txns.append(((trade.trade_date, 1, instrument_id, seq), txn))

    # --- dividends ----------------------------------------------------------
    for seq, (payment, source) in enumerate(
        sorted(inputs.dividends, key=lambda p: (p[0].pay_date, p[1]))
    ):
        commodity = note_commodity(payment.instrument_id, payment.pay_date)
        gross = payment.amount + payment.withholding_tax
        meta = {}
        if payment.external_id:
            meta["dividend_id"] = payment.external_id
        meta["row_hash"] = payment.row_hash
        meta["source"] = source
        meta["commodity"] = commodity
        postings = [
            model.Posting(mapping.cash, _amount(payment.amount, payment.currency)),
        ]
        if payment.withholding_tax:
            postings.append(
                model.Posting(
                    mapping.withholding,
                    _amount(payment.withholding_tax, payment.currency),
                )
            )
        postings.append(model.Posting(mapping.dividends, _amount(-gross, payment.currency)))
        txn = _txn(
            payment.pay_date,
            f"dividend {payment.instrument_id}",
            meta,
            [_link(payment.external_id)] if payment.external_id else [],
            postings,
        )
        txns.append(((payment.pay_date, 2, payment.instrument_id, seq), txn))

    # --- cashflows -----------------------------------------------------------
    for seq, (flow, source) in enumerate(
        sorted(inputs.cashflows, key=lambda f: (f[0].flow_date, f[1]))
    ):
        counter = flow.counter_account or uncategorized
        meta = {}
        if flow.external_id:
            meta["cashflow_id"] = flow.external_id
        meta["row_hash"] = flow.row_hash
        meta["source"] = source
        postings = [
            model.Posting(mapping.cash, _amount(flow.amount, flow.currency)),
            model.Posting(counter, _amount(-flow.amount, flow.currency)),
        ]
        narration = flow.type.value + (f": {flow.notes}" if flow.notes else "")
        txn = _txn(
            flow.flow_date,
            narration,
            meta,
            [_link(flow.external_id)] if flow.external_id else [],
            postings,
        )
        txns.append(((flow.flow_date, 3, seq), txn))

    txns.sort(key=lambda pair: pair[0])
    transactions = [txn for _, txn in txns]

    # --- assertions (checkpoints; dated as_of + 1 day) ------------------------
    assertions: list[model.Directive] = []
    for snapshot in sorted(
        inputs.checkpoint_positions, key=lambda s: (s.as_of, s.instrument_id)
    ):
        commodity = to_commodity(snapshot.instrument_id)
        assertions.append(
            model.Balance(
                snapshot.as_of + ONE_DAY,
                {"checkpoint_date": snapshot.as_of},
                GENERATED_POS,
                mapping.positions,
                _amount(snapshot.quantity, commodity),
            )
        )
    for checkpoint in sorted(
        inputs.checkpoint_cash, key=lambda c: (c.as_of, c.currency)
    ):
        assertions.append(
            model.Balance(
                checkpoint.as_of + ONE_DAY,
                {"checkpoint_date": checkpoint.as_of},
                GENERATED_POS,
                mapping.cash,
                _amount(checkpoint.balance, checkpoint.currency),
            )
        )
    return transactions, assertions, commodity_first_use


def build_files(data_dir: Path) -> BuildResult:
    data_dir = Path(data_dir)
    warnings: list[str] = []
    mapping = load_mapping(data_dir / "bridge" / "mapping.toml")
    inputs = read_inputs(data_dir, warnings)

    files: dict[str, str] = {}
    includes: list[str] = []
    commodity_dates: dict[str, datetime.date] = {}
    open_dates: dict[str, datetime.date] = {}
    open_booking: dict[str, str | None] = {}

    def note_open(account: str, date: datetime.date, booking: str | None = None) -> None:
        first = open_dates.get(account)
        if first is None or date < first:
            open_dates[account] = date
        if booking is not None:
            open_booking[account] = booking

    def add_file(relpath: str, directives: list[model.Directive]) -> None:
        files[relpath] = HEADER + "\n" + format_directives(directives)
        includes.append(relpath)

    for account_id in sorted(inputs):
        acc_inputs = inputs[account_id]
        acc_mapping = mapping.require(account_id)
        transactions, assertions, first_use = _build_account_directives(
            acc_mapping, mapping.opening, mapping.uncategorized, acc_inputs
        )
        for commodity, date in first_use.items():
            if commodity not in commodity_dates or date < commodity_dates[commodity]:
                commodity_dates[commodity] = date
        if transactions:
            earliest = transactions[0].date
            note_open(acc_mapping.positions, earliest, acc_mapping.booking)
            for account in (acc_mapping.cash, acc_mapping.pnl,
                            acc_mapping.dividends, acc_mapping.withholding):
                note_open(account, earliest)

        by_year: dict[int, list[model.Transaction]] = {}
        for txn in transactions:
            by_year.setdefault(txn.date.year, []).append(txn)
        for year in sorted(by_year):
            add_file(f"{account_id}/{year}.beancount", by_year[year])
        if assertions:
            add_file(f"{account_id}/assertions.beancount", assertions)

    preamble: list[model.Directive] = []
    for account in sorted(open_dates):
        preamble.append(
            model.Open(
                open_dates[account], {}, GENERATED_POS, account, (),
                open_booking.get(account),
            )
        )
    for commodity in sorted(commodity_dates):
        preamble.append(
            model.Commodity(
                commodity_dates[commodity],
                {"instrument_id": _instrument_meta(commodity)},
                GENERATED_POS,
                commodity,
            )
        )
    if preamble:
        files["accounts.beancount"] = HEADER + "\n" + format_directives(preamble)
        includes.insert(0, "accounts.beancount")

    index_lines = [HEADER]
    for relpath in includes:
        index_lines.append(f'include "{relpath}"')
    files["index.beancount"] = "\n".join(index_lines) + "\n"
    return BuildResult(files=files, warnings=warnings)


def _instrument_meta(commodity: str) -> str:
    from .commodities import from_commodity

    return from_commodity(commodity)


def generate(data_dir: Path) -> BuildResult:
    """Wholesale-rewrite <data_dir>/ledger/generated/ from the CSVs."""
    data_dir = Path(data_dir)
    result = build_files(data_dir)
    out_dir = data_dir / "ledger" / "generated"
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)
    for relpath, content in sorted(result.files.items()):
        path = out_dir / relpath
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return result
